"""
Shared fonts, colors, spacing constants for a consistent modern look.
"""

FONT_FAMILY = "Segoe UI"

FONT_SIZE_TITLE = 16
FONT_SIZE_NORMAL = 10
FONT_SIZE_HEADING = 12
FONT_SIZE_SMALL = 9

FONT_TITLE = (FONT_FAMILY, FONT_SIZE_TITLE, "bold")
FONT_NORMAL = (FONT_FAMILY, FONT_SIZE_NORMAL)
FONT_HEADING = (FONT_FAMILY, FONT_SIZE_HEADING, "bold")
FONT_SMALL = (FONT_FAMILY, FONT_SIZE_SMALL)
FONT_BUTTON = (FONT_FAMILY, FONT_SIZE_NORMAL, "bold")
FONT_LABEL_CAPS = (FONT_FAMILY, 8, "bold")

# Base palette — slightly richer than pure flat dark
COLOR_BG = "#16171d"
COLOR_BG_HEADER = "#1b1c24"
COLOR_BG_PANEL = "#20212b"
COLOR_BG_CARD = "#262836"
COLOR_BG_CARD_HOVER = "#2d3040"
COLOR_BG_INPUT = "#1b1c24"

COLOR_ACCENT = "#6c8cff"
COLOR_ACCENT_HOVER = "#8199ff"
COLOR_ACCENT_MUTED = "#3a3f5c"

COLOR_DANGER = "#ff5c6c"
COLOR_DANGER_HOVER = "#ff7684"

COLOR_TEXT = "#eceef5"
COLOR_TEXT_MUTED = "#8b8da3"
COLOR_TEXT_FAINT = "#5c5e70"

COLOR_BORDER = "#31333f"
COLOR_KEEPER_BADGE = "#4caf82"
COLOR_SELECTED_BORDER = "#ff5c6c"

PAD_TINY = 2
PAD_SMALL = 6
PAD_MEDIUM = 12
PAD_LARGE = 20
PAD_XLARGE = 28

THUMBNAIL_SIZE = (150, 150)
CORNER_RADIUS = 10